Feature/tgg 51
keeryl/middle.game.praktikum.yandex pull request #12
Opened 2023-06-19 06:51 UTC by go-pro0000

Пересоздавать клиентское Redux-хранилище из серверного.

В момент создания store делаю console.log() с выводом состояния.
На скринах видно, как store создается на клиенте и сервере.

![image](https://github.com/andreysdrv/middle.game.praktikum.yandex/assets/112540409/32835aeb-48a4-4913-b1e4-f66712f7f500)
![image](https://github.com/andreysdrv/middle.game.praktikum.yandex/assets/112540409/607c203f-e5f0-49fb-a1c7-166ba07b40b4)
![image](https://github.com/andreysdrv/middle.game.praktikum.yandex/assets/112540409/f8d3a3a3-0ea9-4bf6-bc64-f97ca47286ac)

2023-06-19 09:10 UTC, keeryl requested changes

2023-06-19 09:10 UTC, keeryl commented on packages/client/src/store/userSelectors.ts
> +//@ts-ignore
Зачем этот игнор?

2023-06-19 16:44 UTC, go-pro0000 commented on packages/server/index.ts
> +      const html = template.replace(`<!--ssr-outlet-->`, appHtml + stateMarkup)
у меня ошибок нет

2023-06-19 16:47 UTC, go-pro0000 commented on packages/client/src/client.d.ts
> +    __REDUX_STATE__?: any;
На сервере создаю тестовый store с поля name email, в storeState таких нет. Чтобы в StoreState ненужные поля не пихать, пока сделал any

2023-06-19 16:47 UTC, go-pro0000 commented on packages/client/src/store/store.ts
> +// export const store = configureStore({
ок

2023-06-19 16:51 UTC, go-pro0000 commented on packages/client/src/store/userSelectors.ts
> +//@ts-ignore
![image](https://github.com/keeryl/middle.game.praktikum.yandex/assets/112540409/941d6819-72d6-4159-8981-81e2e1893e75)

2023-06-21 16:37 UTC, keeryl approved these changes

2023-06-22 18:41 UTC, go-pro0000 commented
@DazzlingFame

2023-06-23 08:04 UTC, DazzlingFame approved these changes
Привет, хорошая работа 👍 
@keeryl тоже отдельное спасибо за крутое ревью!

Я оставил один небольшой комментарий. Поправь его, пожалуйста, и можешь вливать

2023-06-23 08:04 UTC, DazzlingFame commented on packages/client/src/store/userSelectors.ts
> +//@ts-ignore
Напиши тут в комменте над игнором, зачем он нужен / когда поправите его

2023-06-26 06:15 UTC, merged