Feature/tgg 54
keeryl/middle.game.praktikum.yandex pull request #13
Opened 2023-06-23 15:26 UTC by keeryl

### API для форума

2023-06-25 09:29 UTC, Alena-0046 approved these changes

2023-06-25 09:34 UTC, partisan777 requested changes

2023-06-25 09:36 UTC, keeryl commented on packages/server/db.ts
> +};
Это как? Не понял пока

2023-06-25 10:21 UTC, go-pro0000 approved these changes

2023-06-25 14:38 UTC, keeryl commented on packages/server/db.ts
> +};
Перенес env в директорию  db.ts - переменные окружения все равно недоступны. Предлагаю решить этот вопрос в ходе недели доработок.

2023-06-25 14:38 UTC, partisan777 commented on packages/server/db.ts
> +};
ок, сделаем при сборке в докер

2023-06-25 14:38 UTC, partisan777 approved these changes

2023-06-26 07:51 UTC, DazzlingFame approved these changes
Привет, отличная работа! 

Оставил 1 коммент, который стоит поправить перед влитием. Ставлю аппрув, чтобы ты не ждал меня после правки.

2023-06-26 07:51 UTC, DazzlingFame commented on packages/server/tsconfig.json
> +    // "noImplicitOverride": true,
А почему коммент? Это ещё нужно? Если да, то стоит откомментировать, зачем и когда.

2023-06-26 16:28 UTC, keeryl commented on packages/server/tsconfig.json
> +    // "noImplicitOverride": true,
Удалил закомментированный код

2023-06-26 16:28 UTC, merged