сохранение
keeryl/middle.game.praktikum.yandex pull request #4
Opened 2023-06-12 15:04 UTC by partisan777

Настройка Redux и Router в SSR

2023-06-12 15:11 UTC, keeryl requested changes

2023-06-12 15:11 UTC, keeryl commented on packages/server/index.ts
>        let render: () => Promise<string>
В render в index.ts нужно передать url и стор

2023-06-12 15:11 UTC, keeryl commented on packages/client/ssr.tsx
> +  const initialState = store.getState()
Стор нужно создать на сервере

2023-06-12 15:11 UTC, keeryl commented on packages/client/ssr.tsx
> +  const currentRoute = routes.find(route => matchPath(pathname, route))
Вот это не понимаю зачем

2023-06-14 21:24 UTC, go-pro0000 approved these changes

2023-06-15 07:30 UTC, Alena-0046 approved these changes

2023-06-15 07:42 UTC, partisan777 commented on packages/server/index.ts
>        let render: () => Promise<string>
исправлено

2023-06-15 07:42 UTC, partisan777 commented on packages/client/ssr.tsx
> +  const initialState = store.getState()
исправлено

2023-06-15 07:42 UTC, partisan777 commented on packages/client/ssr.tsx
> +  const currentRoute = routes.find(route => matchPath(pathname, route))
исправлено

2023-06-16 07:38 UTC, DazzlingFame commented
Привет, посмотрел новый дифф, не увидел некоторые моменты:
- насколько я вижу по урокам, на этом этапе редакс стор должен конфигурироваться и инициализироваться на сервере, затем начальные данные должны передаваться на клиент
- не увидел реализацию роутинга на сервере через StaticRouter 

Если это не сходит в задачу, вы решили делать как-то по другому или я просто что-то не увидел, отпишись и тегни меня, пожалуйста

2023-06-16 07:50 UTC, partisan777 commented
- роутинг в packages/client/ssr.tsx реализован
- стор конфигурируется аналогично клиенту, но пока что без начальных данных

2023-06-16 07:55 UTC, keeryl commented
> Привет, посмотрел новый дифф, не увидел некоторые моменты:
> 
> * насколько я вижу по урокам, на этом этапе редакс стор должен конфигурироваться и инициализироваться на сервере, затем начальные данные должны передаваться на клиент
> * не увидел реализацию роутинга на сервере через StaticRouter
> 
> Если это не сходит в задачу, вы решили делать как-то по другому или я просто что-то не увидел, отпишись и тегни меня, пожалуйста

Привет!

Я тоже вклинюсь. У нас StaticRouter размещен на клиенте в ssr.tsx., в котором экспортирована функция render, которая принимает url и возвращает результат renderToString. Эта функция вызывается на сервере в index.ts. Такая реализация была в вебинаре Егора Бережного.

По стору - стор сейчас передается в Provider также на клиенте в ssr.tsx. У нас он создается на клиенте с помощью configureStore. В репо практикума с примером ssr стор создается с помощью не библиотечной функции createStore, которая создает редьюсер и возвращает configureStore. Мы c Никитой общались с ментором Ромой на эту тему и он сказал, что можно просто импортировать уже созданный стор и передать его в Provider в ssr.tsx

По поводу передачи данных (initialState) - это насколько я понял отдельная задача (https://linear.app/middle-game-praktikum-yandex/issue/TGG-51/7-sprint-nauchitsya-peresozdavat-klientskoe-redux-hranilishe-iz)

2023-06-16 07:57 UTC, keeryl approved these changes

2023-06-16 08:05 UTC, merged